resilience4j.retry:
    configs:
        default:
            maxAttempts: 1
            waitDuration: 5s
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
                - java.net.SocketException
                - java.net.ConnectException
                - java.lang.Exception
        webdriver:
            maxAttempts: 15
            waitDuration: 1s
            retryExceptions:
                - org.openqa.selenium.WebDriverException
                - org.openqa.selenium.remote.UnreachableBrowserException
                - org.openqa.selenium.NoSuchSessionException
                - org.openqa.selenium.json.JsonException
                - org.openqa.selenium.SessionNotCreatedException
                - java.lang.Exception
                - java.lang.reflect.InvocationTargetException
                - java.io.IOException
                - java.net.ConnectException
                - java.net.SocketException
        neoforj:
            maxAttempts: 3
            waitDuration: 1s
            retryExceptions:
                - org.neo4j.ogm.exception.ConnectionException
                - org.neo4j.driver.exceptions.SessionExpiredException
                - org.neo4j.driver.exceptions.DiscoveryException
                - org.neo4j.driver.exceptions.TransientException
                - org.neo4j.driver.exceptions.ServiceUnavailableException
                - org.neo4j.ogm.exception.TransactionException
                - org.neo4j.ogm.exception.CypherException
                - java.net.SocketException
                - java.util.NoSuchElementException
                - org.springframework.dao.TransientDataAccessResourceException
        gcp:
            maxAttempts: 3
            waitDuration: 1s
            retryExceptions:
                - java.io.IOException
                - com.google.cloud.storage.StorageException
                - com.google.api.gax.rpc.ResourceExhaustedException
                - io.grpc.StatusRuntimeException
                - com.google.api.gax.rpc.UnknownException
                - java.nio.channels.ClosedChannelException
                - java.lang.RuntimeException
                - javax.imageio.IIOException
        builder:
            maxAttempts: 5
            waitDuration: 2s
            retryExceptions:
                - org.openqa.selenium.WebDriverException
                - org.openqa.selenium.remote.UnreachableBrowserException
                - org.openqa.selenium.NoSuchSessionException
                - java.io.IOException
                - java.net.ConnectException
                - java.net.SocketException
    instances:
        neoforj:
            baseConfig: neoforj
        webdriver:
            baseConfig: webdriver
        gcp:
            baseConfig: gcp
        default:
            baseConfig: default
